### ISSUE TITLE
curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by ginterez** [dod-dtic/restful-ocr#7] opened 2019-03-29 13:49 UTC
Why do i get this result when i test the program???

**Comment by seamusminogue** [comment] 2019-03-29 23:12
Without reproducing I would have to guess some kind of error or tesseract was unable to extract any text from the image. 
I haven't had this happen to me so I can't say for sure. Can you give me some more details?

**Comment by ginterez** [comment] 2019-03-31 06:44
When I'm trying to test the program using curl posts, it takes a lot of time to respond but then after the process it does not get any reply from the server. Where I think that it should show or it's output is the text from the image.

**Comment by seamusminogue** [comment] 2019-04-04 17:32
There is no output on the command line where you are running the application? Also, I assume you're using installed tesseract and not trying to use the tesseractjs option?
What version of tesseract are you using? perhaps there is a version incompatibility.

**Comment by sminogue** [comment] 2021-01-13 15:05
Its been over a year without followup or further details so I am going to close this. Most likely this is caused by some kind of internal error and the curl request is timing out. But without more details I cant troubleshoot and I have been unable to reproduce this on my environment.

**Closed by sminogue** 2021-01-13 15:05 UTC
